# Exercise 1.A NumPy: Manipulating Arrays

In [2]:
import numpy as np

# Looping Through Arrays

In [4]:
numbers = [(11, 12, 13),
        (14, 15, 16)]
arrA = np.array(numbers)
print(arrA)

[[11 12 13]
 [14 15 16]]


In [9]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


### The noticeable difference between using for x in arrA with a print(x * 2) is that it prints two columns of variables that have been the result of the originals being multiplied by 2 and the difference in the print(y * 2) is that it gives you one singular line of variables multiplied by 2.

In [11]:
for x in arrA: 
    for y in x: 
        loop_result = x * 2
        print(loop_result)

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## This result is different from the first loop with y because it replicates the results three different times for 22, 24, 26, 28, 30, and 32 rather than just giving us the variables once. It prints three times because it's in a loop and there isn't anything to stop it. 

## Joining and Stacking Arrays

In [15]:
joined_array_1 = np.concatenate([arrA, arrA], axis = 0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [16]:
joined_array_2 = np.concatenate([arrA, arrA], axis = 1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [17]:
stacked_array_1 = np.stack([joined_array_1, joined_array_1], axis = 0)
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [20]:
stacked_array_2 = np.stack([joined_array_1, joined_array_2], axis = 0)
print(stacked_array_2)

# I was given a ValueError that stated all input arrays must have the same shape. 

ValueError: all input arrays must have the same shape

In [21]:
another_joined_array = np.concatenate([joined_array_1, arrA])
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [22]:
another_2 = np.concatenate([joined_array_1, arrA], axis = 1)
print(another_2)

# The error received was a ValueError, which stated that the dimensions of the arrays must be an exact match and this excludes the axis. 

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [23]:
stacked_1 = np.hstack([arrA, arrA])
print(stacked_1)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [24]:
# What the hstack function does is repeat the variables within each square bracket, which is just two, and then stacks them horizontally on top of each other. 

In [25]:
stacked_2 = np.vstack([arrA, arrA])
print(stacked_2)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [26]:
# With the vstack function, it creates duplicates of the array then it stacks them vertically on top of each other. 

In [27]:
stacked_3 = np.dstack([arrA, arrA])
print(stacked_3)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


In [28]:
# Finally, with the dstack function, it separates the duplicates of the variables, such as 11, 12, and 13, then it stacks it on top of the duplicates as well, ordering them from smallest to largest. 

## Splitting Arrays

In [30]:
splitsky = np.split(joined_array_1, 2)
print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


#### Two arrays were produced and each one is a two dimensional array. 

In [32]:
spliterino = np.split(joined_array_1, 3)
print(spliterino)

# This produced a ValueError that stated that this array split would not result in equal division because it has four dimensions in total, which would make it an uneven split. 

ValueError: array split does not result in an equal division

## Searching and Replacing Array Values

In [33]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [40]:
arrB = [(7, 6), 
        (13, 5),
        (7, 3)]
arrB = np.array(arrB)
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [41]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [44]:
print(arrC)
y = arrB >= 7 
arrD = arrB[y]
print(arrD)

[6 5 3]
[ 7 13  7]
