# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [3]:
r_1 = np.random.randint(1, 20, size = 2)
print(r_1)

[ 5 12]


In [6]:
r_2 = np.random.randint(1, 20, size = [1,2])
print(r_2)

[[6 9]]


In [9]:
r_3 = np.random.random(size = [2, 1])
print(r_3)

[[0.47505098]
 [0.44327856]]


In [10]:
r_4 = np.random.randint(20, 100, size = [4, 5])
print(r_4)

[[41 92 80 38 30]
 [66 33 24 77 54]
 [52 36 23 25 26]
 [26 32 68 97 24]]


In [13]:
r_5 = np.random.random(size = [4, 5])
print(r_5)

[[0.68257389 0.05608816 0.13501526 0.41776    0.48906262]
 [0.46210969 0.407526   0.8069745  0.57327413 0.0786148 ]
 [0.01722426 0.57324795 0.48324932 0.90945284 0.33635884]
 [0.82128202 0.75082973 0.29092713 0.28539291 0.74297532]]


## Generating Random Choices from an Array

In [16]:
students = ["Sharleen Guerrero",
             "Sha'Rya Weaver",
             "Vesna Cari",
             "Cris Ramirez",
             "Aspenne Rhoden",
             "Chantal Lee",
             "Demy Melgar", 
             "Dania Kabakibi",
             "Dimitri Nji",
             "Hamzah Alssoudi",
             "Hana Tilahun",
             "Ivana Nwaobi"]

In [17]:
arr1 = np.array(students)
print(arr1)

['Sharleen Guerrero' "Sha'Rya Weaver" 'Vesna Cari' 'Cris Ramirez'
 'Aspenne Rhoden' 'Chantal Lee' 'Demy Melgar' 'Dania Kabakibi'
 'Dimitri Nji' 'Hamzah Alssoudi' 'Hana Tilahun' 'Ivana Nwaobi']


In [19]:
call_on = np.random.choice(students)
print(call_on)

Cris Ramirez


In [21]:
breakout_groups = np.random.choice(students, size = [3, 4])
print(breakout_groups)

# This would not be an effective function to use to create breakout groups because student's names are being repeated more than once for each group and then some students have been excluded from this as well. In essence, this makes this ineffective and it will only lead to confusion unless another function is able to generate different groups for all twelve students listed. 

[['Sharleen Guerrero' 'Sharleen Guerrero' 'Hamzah Alssoudi'
  'Hana Tilahun']
 ['Demy Melgar' 'Vesna Cari' 'Chantal Lee' 'Sharleen Guerrero']
 ['Chantal Lee' 'Aspenne Rhoden' 'Dania Kabakibi' 'Sharleen Guerrero']]


In [24]:
call_on_weighted = np.random.choice(students, size = 5, p = [0.0, 0.1, 0.2, 0.3, 0.1, 0.1, 0.0, 0.1, 0.0, 0.1, 0.0, 0.0])
print(call_on_weighted)

# The reason in which I assigned most of the students 0.0 or even 0.1 is because had I used other values, then the output would have been bigger than 1.0 or 1, which is not what we wanted. So I determined that in order to get 1.0, I would have to stay within the 0.0 to the 0.3 range for numbers. 

['Dania Kabakibi' 'Aspenne Rhoden' 'Cris Ramirez' 'Hamzah Alssoudi'
 'Cris Ramirez']


## Generating a Normal Distribution

In [25]:
bell_curve = np.random.normal(10, 5, size = [4, 5])
print(bell_curve)

[[15.12233351  1.65484637  2.56622495 13.52897089  8.9394716 ]
 [12.91776808  6.9089522  19.79616401  7.6140906   9.87138032]
 [10.96137363  8.91564189 -1.12838442  6.58447054  9.09979902]
 [-2.19175417  7.65282569  5.92424644  9.82384595  5.73165845]]
