# Exercise 1.C Performing operations on arrays

In [5]:
import numpy as np

## Sample Arrays

In [6]:
r_1 = np.random.randint(1, 20, size = 2)
print(r_1)

[16  6]


In [7]:
r_2 = np.random.randint(1, 20, size = [1, 2])
print(r_2)

[[13 17]]


In [8]:
r_3 = np.random.random(size = [2, 1])
print(r_3)

[[0.14946295]
 [0.02715549]]


In [9]:
r_4 = np.random.randint(20, 100, size = [4, 5])
print(r_4)

[[32 23 58 91 99]
 [76 69 81 62 86]
 [88 38 50 21 80]
 [44 73 36 96 20]]


In [10]:
r_5 = np.random.random(size = [4, 5])
print(r_5)

[[0.69462095 0.3829851  0.56495693 0.27020002 0.96065045]
 [0.48116639 0.57305569 0.50634661 0.19497084 0.51883569]
 [0.44074881 0.50887771 0.36301899 0.7577245  0.07964098]
 [0.40555027 0.23758238 0.67752072 0.96054792 0.28293958]]


## Permutations

In [11]:
print(r_4)
shuffle_1 = np.random.shuffle(r_4)
print(r_4)

[[32 23 58 91 99]
 [76 69 81 62 86]
 [88 38 50 21 80]
 [44 73 36 96 20]]
[[76 69 81 62 86]
 [88 38 50 21 80]
 [44 73 36 96 20]
 [32 23 58 91 99]]


### What I found when using np.random.shuffle is that the the rows in the second array are now the oppposite of the first array, which goes from smallest to largest. The second array goes from largest to smallest in the sequence, but none of the variables in the arrays are any different. 

In [12]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print("===========================================================")
print(r_4)

[[32 23 58 91 99]
 [88 38 50 21 80]
 [44 73 36 96 20]
 [76 69 81 62 86]]
[[76 69 81 62 86]
 [88 38 50 21 80]
 [44 73 36 96 20]
 [32 23 58 91 99]]


### The difference that I found between shuffle and permutation is that permutation randomizes the ordering of the numerical values while shuffle just shuffles around the order. Each one does it at random, but permutation really makes it become even more random. 

## Mathematical Operations

In [13]:
print(r_1)
print(r_2)

[16  6]
[[13 17]]


In [14]:
print(r_1.shape)
print(r_2.shape)

(2,)
(1, 2)


In [15]:
result_1 = np.add(r_1, r_2)
print(result_1)
print(result_1.shape)

[[29 23]]
(1, 2)


In [16]:
print(r_1)
print(r_3)

[16  6]
[[0.14946295]
 [0.02715549]]


In [17]:
print(r_1.shape)
print(r_3.shape)

(2,)
(2, 1)


In [18]:
result_2 = np.add(r_1, r_3)
print(result_2)
print(result_2.shape)

[[16.14946295  6.14946295]
 [16.02715549  6.02715549]]
(2, 2)


In [19]:
print(r_2)
print(r_4)

[[13 17]]
[[76 69 81 62 86]
 [88 38 50 21 80]
 [44 73 36 96 20]
 [32 23 58 91 99]]


In [20]:
print(r_2.shape)
print(r_4.shape)

(1, 2)
(4, 5)


In [21]:
result_3 = np.add(r_2, r_4)
print(result_3)
print(result_3.shape)

# This function gave me a ValueError, which stated that they could not be broadcasted together because of shapes (1,2) and (4,5). 

ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [ ]:
print(r_1)
print(r_4)

In [ ]:
print(r_1.shape)
print(r_4.shape)

In [ ]:
result_3 = np.add(r_1, r_4)
print(result_3)

# Adding together r_1 and r_4 produced yet another ValueError, which was the same for when I attempted to add r_2 and r_4 together. This error was caused because the shapes (2,) and (4,5) are incompatible, which I can assume is because the first shape does not have a second numeral within the parentheses. 

In [ ]:
print(r_2)
print(r_3)
print(r_4)

In [ ]:
print(r_2.shape)
print(r_3.shape)

In [ ]:
result_4 = np.add(r_2, r_3)
print(result_4)
print(result_4.shape)

# The results when adding r_2 and r_3 yielded much better results because this time I did not receive a ValueError and I received the results that I expected to receive. This means that the shapes were not incompatible at all and can work properly. 

In [ ]:
print(r_3)
print(r_3.shape)
print(r_4)
print(r_4.shape)

In [ ]:
result_5 = np.add(r_3, r_4)
print(result_5)
print(result_5.shape)

# When I attempted to add r_3 and r_4 together, I received a ValueError this time because the shapes (2,1) and (4,5) are not able to become broadcasted together, which led to the aforementioned error that I received. 

In [ ]:
x = np.add(np.array([1]), r_4)
print(x)

In [ ]:
y = np.add(np.array([[1]]), r_4)
print(y)

In [ ]:
z = np.add(np.array([1, 1, 1, 1, 1]), r_4)
print(z)

In [ ]:
a = np.add(np.array([[1], [1]]), r_4)
print(a)

# For this function or this operation, I received a ValueError because shapes (2,1) and (4,5) could not be broadcasted together, which led to a ValueError being produced. 

#### NumPy uses broadcasting to see if two shapes are compatible before broadcasting them together and allowing them to be added together. What gets added together is the dimensions of the shapes. 

## Rounding

In [ ]:
print(r_3)

In [ ]:
trnc = np.trunc(r_3)
print(trnc)

In [ ]:
fx = np.fix(r_3)
print(fx)

In [ ]:
flr = np.floor(r_3)
print(flr)

In [ ]:
cil = np.ceil(r_3)
print(cil)

In [ ]:
rnd = np.round(r_3, 2)
print(rnd)

## Cumulative Operations

In [ ]:
print(r_4)

In [ ]:
a = np.sum(r_4)
print(a)

In [ ]:
b = np.sum(r_4, axis = 0)
print(b)

In [ ]:
c = np.sum(r_4, axis = 1)
print(c)

In [ ]:
d = np.cumsum(r_4)
print(d)

In [ ]:
e = np.cumsum(r_4, axis = 0)
print(e)

## Grocery Problem

In [ ]:
bag1 = [2, 3, 4, 0]
bag2 = [4, 0, 1, 2]

# for bag1: 2 = vegetables, 3 = fruits, 4 = boxes of snacks, 0 = no beverages
# for bag2: 4 = vegetables, 0 = no fruits, 1 = box of snacks, 2 = beverages

In [22]:
gb1 = np.array(bag1)
print(gb1)

print("===================================================")

gb2 = np.array(bag2)
print(gb2)

[2 3 4 0]
[4 0 1 2]


In [23]:
grocery_a = np.sum(gb1)
grocery_b = np.sum(gb2)

print("===================================================")

print(f"The first bag contains {grocery_a} items, and the second bag contains {grocery_b} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [26]:
grocery_c = np.add(gb1, gb2)
print(f"There are {grocery_c[0]} vegetables, {grocery_c[1]} fruits, {grocery_c[2]} boxes of snacks, and {grocery_c[3]} beverages in two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in two grocery bags.


## Teamwork

In [27]:
Ali = [5, 4, 6, 4, 2]
Ben = [0, 5, 5, 3, 4]
Carla = [3, 6, 0, 3, 4]

In [33]:
Ali_1 = np.array(Ali)
print(Ali_1)

print("=====================================================")

Ben_1 = np.array(Ben)
print(Ben_1)

print("======================================================")

Carla_1 = np.array(Carla)
print(Carla_1)

[5 4 6 4 2]
[0 5 5 3 4]
[3 6 0 3 4]


In [35]:
all_knocks = np.vstack([Ali_1, Ben_1, Carla_1])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [36]:
knocks_1 = np.sum(all_knocks, axis = 1)
print(knocks_1)

[21 17 16]


In [37]:
knocks_2 = np.sum(all_knocks)
print(knocks_2)

54


In [39]:
knocks_3 = np.cumsum(all_knocks, axis = 0)/2
print(knocks_3)

[[2.5 2.  3.  2.  1. ]
 [2.5 4.5 5.5 3.5 3. ]
 [4.  7.5 5.5 5.  5. ]]
